import * as React from "react"
import { Link } from "gatsby"
import { StaticImage } from "gatsby-plugin-image"
import VideoTest from "../images/WebIntro_cc.mp4"

import Layout from "../components/layout"
import SEO from "../components/seo"

const IndexPage = () => (
  <Layout>
    <SEO title="Home" />
    
    <h1>Hi people</h1>
    <video autoPlay loop muted src={VideoTest} id="introVideo"></video>
    <p>Welcome to your new Gatsby site.</p>
    <p>Now go build something great.</p>
    <p>
      <Link to="/page-2/">Go to page 2</Link> <br />
      <Link to="/using-typescript/">Go to "Using TypeScript"</Link>
    </p>

    <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis hendrerit ut nulla et eleifend. Praesent hendrerit tristique pretium. Aliquam tristique risus in nulla vehicula, id dapibus nisi consequat. Fusce ullamcorper ante et purus imperdiet egestas a a purus. Proin ligula massa, laoreet non libero sit amet, finibus euismod urna. Nunc eget lacus sit amet odio consectetur tempus vitae at neque. Donec justo odio, commodo in pretium at, tincidunt quis dui. Nam iaculis nulla eget faucibus vulputate. Suspendisse potenti. Suspendisse ut mauris turpis. Aliquam sagittis viverra ultrices. Nunc laoreet lacus quis nulla luctus pretium. Phasellus fringilla, risus eleifend auctor posuere, odio erat mollis mauris, vel euismod odio urna scelerisque libero. Pellentesque varius elit est, eget tempor metus tempus in. In facilisis eleifend massa ac ultricies.

Vestibulum ac auctor odio. Fusce in convallis mauris, non ornare nunc. Nullam velit ex, euismod ac posuere ut, facilisis ac augue. Quisque suscipit ex tellus, nec dignissim dui congue sed. Donec vitae mi sed augue vestibulum facilisis. Aliquam posuere sapien odio, sit amet mollis orci consequat viverra. Nunc nec lectus nisi. Nullam rhoncus felis eros. Duis at dolor eget enim semper auctor. Donec ut vehicula enim, a finibus diam. Donec non mattis tellus. Etiam non dui lacinia dolor gravida mollis. Sed justo diam, pretium sed leo nec, dignissim tincidunt libero. Duis ut eros eget est finibus commodo. In imperdiet diam sed lorem accumsan congue vel a diam.

Donec porta vestibulum eleifend. Donec bibendum ultrices tortor, eget condimentum arcu ultricies vel. Nulla id mauris augue. Aliquam egestas ante nisl, sit amet ultrices sem sollicitudin et. Mauris at eros mollis, volutpat lacus quis, hendrerit arcu. Pellentesque porttitor feugiat enim. Morbi luctus gravida orci eget cursus. Fusce pellentesque orci vel gravida dapibus. Sed feugiat iaculis purus, sed sollicitudin tortor ullamcorper vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In hac habitasse platea dictumst. Nunc pulvinar, nibh vitae scelerisque pretium, mi elit molestie leo, eget interdum enim purus vitae enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce efficitur, libero eget tristique fermentum, enim tortor finibus odio, sed ullamcorper sem magna a neque. Aliquam quam mi, volutpat eu efficitur a, suscipit quis tortor.

Morbi sed maximus est. In ipsum enim, volutpat aliquet eleifend quis, dignissim vitae sapien. Nulla ullamcorper quam lacus, non vehicula metus scelerisque in. Donec eget elementum lacus, vitae congue tellus. Duis augue eros, pellentesque vel semper eu, sodales sed nulla. Mauris molestie dapibus facilisis. Suspendisse egestas porttitor ex.

Mauris maximus luctus efficitur. Curabitur at eleifend orci, vitae malesuada ante. Donec eu nulla vel purus consequat fermentum. Nulla quis leo maximus, tincidunt neque id, dapibus risus. Nulla ac nulla metus. Nullam nec consequat magna, et tristique turpis. Praesent sapien orci, euismod ut volutpat et, efficitur a massa. Integer vestibulum urna vitae tellus luctus, sed egestas leo molestie. Sed consectetur urna vel ex bibendum, non sagittis mi ultricies. Suspendisse potenti. Duis scelerisque ullamcorper diam, vel pretium sem malesuada id. Nullam et ligula nibh. Proin eu urna porttitor, condimentum diam a, tempus leo. Nullam luctus metus ac erat sodales, in lobortis odio tincidunt. Duis lobortis ex nec urna rhoncus, ac molestie felis iaculis.

Quisque mauris sem, finibus vitae odio in, viverra laoreet arcu. Sed ut pretium ante. Integer vitae cursus enim, ac semper sapien. Donec efficitur sem in finibus consectetur. Phasellus sed pellentesque dolor. Donec dapibus, magna in facilisis laoreet, enim enim faucibus tortor, eu elementum magna quam at felis. Morbi massa tellus, vestibulum ut erat eget, luctus tempor metus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque rutrum quam ex, et congue tortor volutpat a. Nulla tempor quam nunc, vel elementum quam malesuada id. Morbi pretium diam at arcu commodo varius. Donec porttitor libero ac eros bibendum rutrum.

Fusce luctus nunc non eros convallis, in sodales orci venenatis. Nullam accumsan lectus eget lacus eleifend tempus. Proin ipsum massa, sollicitudin ut lectus aliquam, bibendum faucibus enim. Nunc vitae metus eget est dictum dapibus. Ut tortor turpis, fringilla eu tempus viverra, fermentum nec orci. Morbi faucibus turpis ut nibh volutpat auctor. Sed interdum nisi et eros convallis, eget lacinia justo blandit. Donec et nulla sit amet lacus posuere tincidunt.

Nunc et dolor diam. Aenean pharetra metus fermentum nunc blandit tempus. Vestibulum quis arcu et ligula convallis iaculis. Sed convallis augue et metus viverra commodo. Donec accumsan rutrum laoreet. Nullam non maximus ante, sed ullamcorper orci. Mauris eget pretium orci. Nam eleifend suscipit elit congue dapibus. Sed maximus tellus quis volutpat euismod. Sed et commodo risus, sed maximus sapien. Nunc a sapien nec velit pulvinar congue at vel metus. Suspendisse nec quam nibh. Ut dolor enim, pellentesque tempor dolor eu, vehicula vehicula nibh.

Nulla pharetra tempor quam sit amet scelerisque. Proin consectetur vulputate augue, ac varius risus egestas ac. In quis mi ante. Praesent quis metus tortor. Pellentesque a ornare eros. In iaculis eros non dui eleifend, ac volutpat ligula lacinia. Sed nec porta metus. Vestibulum vitae mollis nunc.

Sed ac egestas purus. Integer placerat tristique neque vel aliquam. Maecenas sodales nunc id dui scelerisque, eget varius ligula convallis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque pellentesque, elit in elementum pulvinar, dolor arcu rhoncus odio, sit amet bibendum erat neque non lectus. In bibendum rutrum nisl eu ullamcorper. Suspendisse neque risus, luctus vehicula facilisis eget, dapibus non urna. Aliquam ligula neque, scelerisque sit amet felis eu, venenatis pretium urna. Ut consequat dictum cursus. Duis vel tellus ultricies, gravida ante at, iaculis urna. Sed sed rutrum neque, ut posuere felis. Proin nec consectetur mi. Mauris sit amet posuere neque, eu mattis sem.

Suspendisse id nisi vitae lorem laoreet vestibulum. Sed est sapien, mollis vitae est ornare, vehicula fermentum purus. Cras facilisis dui massa. Nulla nec rutrum nibh. Phasellus id odio nibh. Sed a tempus libero, a fringilla turpis. Duis auctor leo vitae urna placerat, vitae dictum sem consequat. Nunc quis lorem facilisis, scelerisque arcu a, iaculis magna. Mauris nec diam ut lorem aliquam efficitur. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Etiam tincidunt justo tortor, at commodo justo vehicula at. Phasellus sit amet est sit amet enim finibus varius. Nunc a dolor eget eros euismod facilisis. Morbi aliquam sodales purus nec sodales. Fusce luctus, sapien vitae vehicula consequat, dui nulla fermentum dui, at maximus leo augue et arcu. Integer ultricies non lacus nec vulputate.

Mauris dictum convallis neque sit amet porta. Vivamus dictum euismod mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque a interdum nunc, nec hendrerit mi. Phasellus semper lacus vel erat faucibus tincidunt. Etiam blandit congue hendrerit. Donec feugiat sed justo a dapibus.

Aliquam vitae urna placerat, elementum orci eu, vulputate nibh. In ligula erat, rutrum sed ligula finibus, elementum placerat quam. Sed mauris velit, iaculis et efficitur eget, volutpat quis elit. Duis venenatis vehicula tellus id consequat. Suspendisse consectetur molestie nisi, gravida sagittis massa venenatis eu. Vivamus vitae dui lacus. Cras nulla urna, commodo a ullamcorper id, faucibus vitae mi. Vestibulum quis leo mi. Mauris elementum libero sed tellus tincidunt fermentum. Vivamus tincidunt bibendum massa, in pharetra nisi. Aliquam ultricies leo ac maximus ultricies. Praesent aliquet massa id lacus luctus, et facilisis ipsum tristique. Curabitur in maximus libero. Phasellus sollicitudin ante non urna consequat sodales. Maecenas fringilla non mauris sed posuere.

Morbi a elit tortor. Maecenas vitae egestas libero, a pharetra lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras malesuada feugiat nisi a aliquet. Etiam condimentum ante et nibh euismod, in pretium quam elementum. Quisque interdum id risus sed aliquet. Praesent vitae aliquam sapien. Nam ac dignissim nisi. Etiam sit amet imperdiet velit, eu egestas dui. Duis at mi justo. Nam at dictum est.

Donec tempus consequat nisi, eget fringilla risus efficitur et. Phasellus bibendum ut nisi nec laoreet. Nunc aliquam libero ut nunc condimentum iaculis. Aenean commodo semper turpis at vulputate. Nullam eget urna sem. Sed dapibus scelerisque rutrum. Aenean sagittis ut est vitae maximus. Donec est nulla, sodales nec rutrum ac, vehicula et metus. Vestibulum est lectus, scelerisque non mollis ac, fringilla quis odio.

Maecenas blandit arcu feugiat quam pellentesque bibendum. Sed in massa eleifend, aliquam lectus ac, vulputate velit. Fusce eu nulla egestas, placerat tellus porta, elementum enim. Cras a quam dapibus, consectetur dolor nec, maximus ligula. Nullam turpis eros, luctus at rhoncus non, dapibus vel justo. Ut cursus cursus magna eu tincidunt. Proin varius auctor quam quis iaculis. Vestibulum pellentesque justo et dui congue eleifend.

Nulla dignissim dui quis tortor bibendum, ac pharetra velit fermentum. Nullam vel iaculis ipsum, in porttitor ipsum. Cras blandit arcu vitae lacus consectetur consectetur. Etiam nec gravida ante. Curabitur rutrum mattis nisi sit amet porta. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras posuere lectus non feugiat interdum. Etiam sagittis congue efficitur. Suspendisse quis arcu malesuada, consectetur enim vel, pellentesque nunc. Fusce vel rhoncus neque. Sed varius turpis vel nisl molestie, a iaculis lectus pharetra. Integer velit orci, placerat a ornare ut, cursus vel sapien.

Fusce non arcu ligula. Integer in rhoncus elit. Cras quis ex pulvinar, tincidunt felis vel, dignissim odio. Nulla mollis gravida nisl, id pretium sem fermentum non. Curabitur nec vestibulum sem. Curabitur a accumsan magna, facilisis rhoncus orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris semper, sem eu tempus aliquet, leo mauris dapibus mi, non commodo eros mi a magna. Cras accumsan tortor libero, sit amet pharetra metus ultrices non. Donec eu quam auctor, congue orci et, finibus nulla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas vitae rhoncus elit, ultricies dignissim ipsum.

Integer pretium arcu sem, eu molestie orci dignissim vel. Sed tristique porta bibendum. Integer enim est, lobortis a porttitor et, lacinia ac ligula. Sed id magna a metus pellentesque lacinia ut vel lorem. Sed rutrum, nulla sit amet fermentum lacinia, diam mauris suscipit urna, nec accumsan tortor nunc sit amet nunc. Morbi ornare purus est, sed ornare ex blandit id. Pellentesque pellentesque urna id magna pharetra, ut rhoncus massa elementum. Aenean in fringilla libero. Praesent ac aliquet nulla, nec molestie eros. Etiam purus nunc, commodo in sollicitudin et, ultricies eu lorem.

Praesent et bibendum sem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent finibus lobortis semper. Nulla tristique turpis nec mi molestie mollis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur posuere nisi et egestas finibus. Donec vitae sapien nec lorem fringilla gravida. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Sed ut tortor consectetur, volutpat dolor ut, iaculis ex. Vivamus consectetur urna vitae purus dignissim, at venenatis quam ultrices. Suspendisse nec viverra enim, at fermentum ex. Donec sed tincidunt quam. Pellentesque suscipit dui vel rhoncus efficitur. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi urna dui, sollicitudin et rutrum non, rhoncus eu ante. Donec pharetra neque vel arcu ultrices, et iaculis est hendrerit. Vestibulum ac dignissim sapien, ut dignissim nibh. Fusce eu magna elementum, scelerisque eros id, accumsan lorem. Quisque maximus arcu quis neque fermentum, quis mollis justo aliquet. Donec eros tortor, lobortis et ornare ut, rutrum a felis. Duis purus turpis, pharetra vitae volutpat a, rutrum eget tortor.

Praesent placerat laoreet quam et tempor. Nunc in metus risus. Maecenas ac metus aliquam, placerat sem eget, volutpat elit. Sed tristique porttitor congue. Quisque ac leo vel orci efficitur pharetra quis sed nisi. Donec pellentesque ultrices facilisis. Vestibulum egestas lectus a erat viverra blandit. Maecenas varius massa at sapien accumsan tristique. Donec ut venenatis nibh. Ut massa ipsum, venenatis in tincidunt ac, porttitor sit amet urna. Fusce at sem in risus elementum interdum eget vitae mauris. Suspendisse vel tristique ipsum. Suspendisse hendrerit elit erat. Vestibulum ut mattis nunc. Phasellus sodales efficitur orci in porttitor.

Nunc at suscipit mauris, ac tempus leo. Suspendisse et lobortis turpis, eget ornare urna. Fusce pulvinar mi tortor, et porttitor lorem aliquet in. Duis ex quam, hendrerit ac dui nec, fermentum sagittis urna. Nullam a pretium urna. Etiam faucibus magna at nunc rhoncus, at aliquet diam elementum. Quisque egestas interdum nibh, gravida fermentum sapien pharetra ac. Sed consectetur, orci vel placerat varius, risus massa gravida elit, non facilisis nisi arcu consequat tortor. Vivamus porta bibendum massa, tincidunt semper arcu consectetur non. Vivamus ultrices orci at tristique luctus. Sed at ipsum elit. Duis mattis ipsum et libero dignissim, sit amet gravida metus varius. Quisque volutpat diam vitae maximus tempor. Vivamus sed vehicula augue. Quisque risus sapien, cursus sit amet commodo feugiat, tempus ullamcorper elit.

Vivamus dictum metus at diam sollicitudin laoreet. Sed ac condimentum urna. Curabitur non erat eu quam sollicitudin iaculis. Etiam euismod sagittis luctus. Nunc sed orci odio. Donec ut neque ex. Phasellus consectetur turpis turpis, tincidunt lacinia turpis aliquet a. Donec id massa quis nibh porta pellentesque. Aliquam lobortis risus vitae justo ornare, sed convallis justo consectetur. Vivamus tincidunt sem bibendum tortor tempor lobortis. Cras nec est a ex eleifend mattis.

Integer id ante accumsan massa ultrices consectetur in sed magna. Vivamus bibendum blandit ante id posuere. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vulputate porta fermentum. Aenean egestas, ex nec aliquet aliquet, eros justo auctor diam, at consequat justo nisi ut dui. Etiam facilisis porta fringilla. In nec ultrices tellus. Etiam semper lacinia eleifend. In nulla felis, accumsan id rutrum et, imperdiet et lacus. Nam dui sem, sollicitudin eget interdum ut, vehicula quis neque. Donec lorem libero, interdum a auctor sed, fermentum eget eros. Nulla facilisi. Etiam efficitur tempor dolor. Phasellus porttitor porta molestie. Sed efficitur nulla vitae nibh tempus, sed tempus metus sollicitudin.

Quisque egestas lorem et enim aliquet luctus. Praesent feugiat quis sapien ac fermentum. Phasellus pharetra sapien a quam tincidunt, sit amet fermentum est scelerisque. Nulla feugiat ultrices leo, sit amet vestibulum eros vestibulum non. Duis vel elementum nisi. Mauris viverra lacus urna, a dapibus tellus imperdiet sit amet. Curabitur in cursus lorem. Proin suscipit bibendum nunc a vestibulum. Curabitur convallis quam vitae augue ultricies, nec semper massa interdum. Cras nibh urna, blandit convallis dapibus vitae, molestie vitae erat. Vivamus aliquet massa urna, quis luctus libero interdum eu.

Suspendisse quis egestas libero. Curabitur ut mollis ipsum. Phasellus bibendum ligula sed ante elementum vehicula. Proin molestie suscipit mi quis pulvinar. Mauris malesuada sem a sapien accumsan, ac pellentesque metus vulputate. Nulla a interdum nisl. Cras at tincidunt massa. Fusce eu commodo odio.

Integer rutrum finibus lorem. Aliquam placerat nisi cursus ex ultrices rhoncus ac at arcu. Fusce cursus feugiat gravida. Proin tempor diam a mi accumsan, nec sollicitudin diam fermentum. Donec euismod purus nec lectus euismod euismod. Morbi dapibus, est eget tempus ullamcorper, ante velit convallis sem, a placerat purus nibh vel sem. Suspendisse pretium, nisl nec vulputate consectetur, diam augue dignissim tellus, et ullamcorper nisl erat ultricies erat.

Donec eu eros fringilla, sagittis ligula at, dignissim lorem. Pellentesque lobortis nisl at dui consectetur, eget blandit tortor volutpat. Aliquam tincidunt consectetur erat, sed mollis dui. Vivamus accumsan venenatis consectetur. Nulla pretium, lorem sed gravida tincidunt, ipsum elit volutpat velit, in consectetur lectus sem in ex. Pellentesque velit urna, pulvinar vel pulvinar ac, viverra eget nulla. Cras vitae augue molestie, gravida odio nec, pellentesque ligula. Sed sed tincidunt est, sed scelerisque leo.

Proin ullamcorper ligula in ipsum volutpat, at tincidunt elit maximus. Vestibulum vitae porttitor lorem. Vestibulum vitae enim ullamcorper, tempus erat ac, commodo nisl. Curabitur ligula ligula, facilisis quis odio id, finibus varius magna. Maecenas volutpat enim a lacinia bibendum. Vestibulum tempus dui tellus, eu eleifend lectus semper sed. Ut quis elementum lorem, eget aliquam leo. Aliquam sollicitudin aliquet consectetur. Nulla porta eget metus imperdiet faucibus. Morbi suscipit tellus eget purus cursus, id convallis ante ullamcorper. Fusce condimentum venenatis magna, a mattis massa pharetra quis.
    </p>
  </Layout>
)

export default IndexPage
