# This is a basic workflow to help you get started with Actions

name: Build and deploy to FTP

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: Install Project Dependencies
        run: npm ci
        
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@3.2.0
        
      - name: Build
        run: gatsby build && cd build
        
      - name: Sign into sftp
        run: |
          sftp -P 23 ${{ FTP_USER }}@fentker.com
          ${{ FTP_PASSWORD }}
          cd web
          rm -rf jet && mkdir jet && cd jet
          lcd public
          put -r .
          

              
